name: Validate PR

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for checking changed files
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Run unit tests with coverage
        run: npm run test:coverage -- --coverage.thresholds.lines=100 --coverage.thresholds.branches=95 --coverage.thresholds.functions=95 --coverage.thresholds.statements=95
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          CI: true
      
      - name: Check for updated e2e expectations
        run: |
          # Check if any files in tests/e2e/user-stories have been modified by the test run
          if ! git diff --exit-code --quiet tests/e2e/user-stories/; then
            echo "Error: E2E test expectations have been updated during test run."
            echo "The following expectation files were modified:"
            git diff --name-only tests/e2e/user-stories/
            echo ""
            echo "This means the screenshots generated by the tests don't match the committed expectations."
            echo "All screenshots must match 100% - none should need to be regenerated."
            exit 1
          else
            echo "All e2e screenshots match expectations (100%). ✓"
          fi
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7
